############################# Portuguese ############################
[pt]
languageName = "pt"
title = "Mamão na Roda"
contentDir = "content/portuguese" # content/german
weight = 0

########### footer content ##########
footer_menu_left = "Iniciativa"
footer_menu_middle = "Livros"
footer_menu_right = "Suporte"
footer_content = "Siga-nos."

# copyright
copyright = "© 2021 Mamão na Roda."
