# main menu
[[main]]
name = "Início"
url = "/"
weight = 1

[[main]]
name = "Livros"
url = "book"
weight = 2

[[main]]
name = "Blog"
url = "blog"
weight = 3

[[main]]
name = "Sobre"
url = "about"
weight = 4

# footer menu left
[[footer_left]]
name = "Sobre"
url = "about"
weight = 1

[[footer_left]]
name = "Dúvidas"
url = "faq"
weight = 2

[[footer_left]]
name = "Contato"
url = "contact"
weight = 3

[[footer_middle]]
name = "Auditoria Volume 1 2020"
url = "book/book-1"
weight = 1
