#################### default parameters ################################
logo = "images/logo.png"
logo_width = "200px"
# OpenGraph / Twitter Card metadata
description = "Site Mamão na Roda"
author = "Mamão na Roda"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Type of pages to be rendered with a blog view
blogCategoryType = "category"

# Preloader
[preloader]
enable = false
preloader = "svg" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "Amostra grátis"
link = "book"

# cookies
[cookies]
enable = false
expire_days = 365
content = "Este site usa cookies. Para continuar navegando, segundo a lei vigente, você precisa concordar."
button = "Eu aceito"
  
############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/MamaoNaRodaConcursos"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://www.twitter.com/mamaonaroda"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/mamaonaroda/"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/mamaonaroda/"