---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Homepage
- type: document
  path: site_mamaonaroda/content/portuguese/_index.md
  label: Início
- type: heading
  label: Blog
- type: document
  path: site_mamaonaroda/content/portuguese/blog/_index.md
  label: Página de Blog
- type: directory
  path: site_mamaonaroda/content/portuguese/blog
  label: Blog Post
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: heading
label: Books
- type: document
  path: site_mamaonaroda/content/portuguese/book/_index.md
  label: Livros
- type: directory
  path: site_mamaonaroda/content/portuguese/book
  label: Livro
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - book
- type: heading
  label: Others Page
- type: document
  path: site_mamaonaroda/content/portuguese/contact/_index.md
  label: Contato
- type: document
  path: site_mamaonaroda/content/portuguese/pricing/_index.md
  label: Preços
- type: document
  path: site_mamaonaroda/content/portuguese/faq/_index.md
  label: FAQ 
- type: heading
  label: All Pages
- type: directory
  path: site_mamaonaroda/content
  label: All Pages
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - new-page
- type: heading
  label: Configuration
- type: document
  path: site_mamaonaroda/config/_default/config.toml
  label: Configuration
- type: document
  path: site_mamaonaroda/config/_default/params.toml
  label: Parameters
- type: document
  path: config.toml
  label: Variables & Plugins
  match: "**/*"
- type: document
  path: site_mamaonaroda/config/_default/languages.toml
  label: Languages
- type: document
  path: site_mamaonaroda/config/_default/menus.pt.toml
  label: Menu (en)
- match: "**/*"
upload_dir: site_mamaonaroda/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
